import fs from 'fs';
import path from 'path';

const enPath = path.resolve('src/i18n/locales/en.json');
const en = JSON.parse(fs.readFileSync(enPath, 'utf8'));

// Dictionaries with key translations for all top 20 languages
const langPacks = {
  fr: {
    "common": { "save": "Enregistrer les modifications", "cancel": "Annuler", "delete": "Supprimer", "edit": "Modifier", "create": "Créer", "add": "Ajouter", "remove": "Retirer", "search": "Rechercher...", "filter": "Filtrer", "sort": "Trier", "back": "Retour", "next": "Suivant", "continue": "Continuer", "loading": "Chargement...", "error": "Une erreur est survenue", "success": "Succès", "retry": "Réessayer", "close": "Fermer", "preview": "Aperçu", "duplicate": "Dupliquer", "archive": "Archiver", "actions": "Actions", "refresh": "Actualiser", "status": "Statut", "active": "Actif", "inactive": "Inactif", "yes": "Oui", "no": "Non", "select": "Sélectionner", "reset": "Réinitialiser", "optional": "Optionnel", "required": "Requis", "all": "Tous", "none": "Aucun", "units": "Unités", "cm": "CM", "in": "PO", "items": "{{count}} éléments", "productsCount": "{{count}} produits", "categoriesCount": "{{count}} catégories", "rows": "Lignes", "columns": "Colonnes" },
    "navigation": { "overview": "Aperçu", "charts": "Tableaux des tailles", "assignments": "Attributions", "fitFinder": "Guide de coupe", "analytics": "Statistiques", "settings": "Paramètres", "general": "Général", "widget": "Design du widget", "localization": "Localisation", "billing": "Facturation et forfaits", "data": "Données et sauvegarde", "help": "Aide et documentation", "currentPlan": "Forfait actuel" },
    "overview": { "title": "Stores Size Chart & Fit Guide", "subtitle": "Créez des tableaux de tailles professionnels et aidez vos clients à trouver la coupe idéale.", "kpis": { "totalCharts": "Total des tableaux", "activeCharts": "Tableaux actifs", "productsWithCharts": "Produits avec tableau", "productsWithoutCharts": "Produits sans tableau", "sizeGuideViews": "Vues du guide de taille", "fitFinderUses": "Utilisations du guide de coupe", "completionRate": "Taux de complétion", "mostViewedChart": "Tableau le plus vu", "mostRecommendedSize": "Taille la plus recommandée" }, "quickActions": "Actions rapides", "createChart": "Créer un tableau", "assignCharts": "Attribuer des tableaux", "customizeWidget": "Personnaliser le widget", "configureFitFinder": "Configurer le guide de coupe" },
    "pluginStatus": { "title": "État du widget Guide des tailles", "active": "Actif", "notAdded": "Configuration requise", "checking": "Vérification...", "error": "Échec de vérification", "descriptionActive": "Votre guide des tailles est installé sur votre page produit Wix Stores.", "descriptionNotAdded": "Ajoutez le guide des tailles à votre page produit pour que vos clients puissent y accéder.", "descriptionError": "Impossible de vérifier l'emplacement du widget.", "manage": "Gérer dans l'Éditeur", "add": "Ajouter le guide", "retry": "Réessayer", "addSuccess": "Guide des tailles ajouté avec succès à votre page produit", "addError": "Impossible d'ajouter automatiquement le plugin.", "warningMissing": "Vos tableaux sont actifs mais le widget n'est pas placé sur votre page produit." },
    "charts": { "title": "Tableaux des tailles", "subtitle": "Gérez l'ensemble des guides de tailles et de mesures pour votre catalogue.", "create": "Créer un tableau", "searchPlaceholder": "Rechercher un tableau...", "filterType": "Tous les types", "filterStatus": "Tous les statuts", "allTypes": "Tous les types", "allStatuses": "Tous les statuts", "emptyTitle": "Aucun tableau pour le moment", "emptyDescription": "Créez votre premier tableau pour aider vos clients.", "deleteConfirmTitle": "Supprimer le tableau ?", "deleteConfirmDesc": "Êtes-vous sûr de vouloir supprimer '{{name}}' ?", "tableHeaderName": "Nom du tableau", "tableHeaderType": "Catégorie / Type", "tableHeaderUnit": "Unité par défaut", "tableHeaderAssignments": "Attributions", "tableHeaderFitFinder": "Guide de coupe", "tableHeaderStatus": "Statut", "tableHeaderUpdated": "Dernière mise à jour" },
    "builder": { "titleEdit": "Modifier le tableau", "titleCreate": "Créer un nouveau tableau", "basicInfo": "Informations de base", "chartName": "Nom du tableau", "chartNamePlaceholder": "Ex. Chemise Oxford Homme", "chartType": "Type de vêtement", "description": "Note client / Description", "descriptionPlaceholder": "Conseils de coupe affichés au-dessus du tableau...", "defaultUnitLabel": "Unité d'affichage par défaut", "tableSection": "Éditeur de tableau de tailles", "addRow": "Ajouter une ligne", "addColumn": "Ajouter une colonne", "duplicateRow": "Dupliquer la ligne", "duplicateColumn": "Dupliquer la colonne", "deleteRow": "Supprimer la ligne", "deleteColumn": "Supprimer la colonne", "renameColumn": "Renommer la colonne", "columnName": "Titre de colonne", "columnPreset": "Ajouter une mesure type", "customColumn": "Mesure personnalisée", "measurementGuideSection": "Guide de prise de mesures", "addInstruction": "Ajouter un guide", "removeInstruction": "Retirer le guide", "instructionTitle": "Zone de mesure", "instructionDesc": "Détails de l'instruction", "templatesSection": "Charger un modèle", "chooseTemplate": "Sélectionner un modèle...", "importCsv": "Importer CSV", "exportCsv": "Exporter CSV", "pasteData": "Coller les données", "unsavedChangesWarning": "Vous avez des modifications non enregistrées.", "saveChart": "Enregistrer le tableau", "previewChart": "Aperçu en direct", "enterValue": "Valeur" },
    "fitFinder": { "title": "Smart Fit Finder", "subtitle": "Recommandations de taille déterministes basées sur les mesures du client.", "statusToggle": "Activer Fit Finder pour ce tableau", "storefrontTitle": "Trouver ma taille", "stepOf": "Étape {{current}} sur {{total}}", "continueBtn": "Continuer", "backBtn": "Retour", "calculateBtn": "Calculer ma taille", "recommendedSizeTitle": "Votre taille recommandée", "closestMatchDesc": "Selon vos mesures, la taille {{size}} est la plus adaptée.", "betweenSizesTitle": "Vous êtes entre deux tailles", "betweenSizesDesc": "Voici les deux meilleures options :", "closerFit": "{{size}} pour une coupe plus ajustée", "moreRelaxedFit": "{{size}} pour une coupe plus décontractée", "selectSizeBtn": "Sélectionner la taille {{size}}", "startOverBtn": "Recommencer", "noRecommendation": "Calcul impossible avec ces mesures." },
    "billing": { "currentPlanTitle": "Statut de l'abonnement", "starterPlan": "Forfait Starter", "proPlan": "Forfait Pro", "trialActive": "Essai gratuit actif", "trialAvailable": "Essai gratuit disponible", "daysRemaining": "{{count}} jours d'essai restants", "subscriptionActive": "Abonnement actif", "subscriptionCancelled": "Annulation en attente", "activeUntil": "Actif jusqu'au {{date}}", "trialExpired": "Essai gratuit expiré", "paidExpired": "Abonnement expiré", "billingUnknown": "Statut de facturation inconnu", "startTrialBtn": "Démarrer l'essai gratuit", "subscribeBtn": "S'abonner maintenant", "resubscribeBtn": "Réactiver l'abonnement", "reactivateBtn": "Réactiver", "choosePlanBtn": "Choisir un forfait" }
  },
  de: {
    "common": { "save": "Änderungen speichern", "cancel": "Abbrechen", "delete": "Löschen", "edit": "Bearbeiten", "create": "Erstellen", "add": "Hinzufügen", "remove": "Entfernen", "search": "Suchen...", "filter": "Filtern", "sort": "Sortieren", "back": "Zurück", "next": "Weiter", "continue": "Fortfahren", "loading": "Wird geladen...", "error": "Ein Fehler ist aufgetreten", "success": "Erfolg", "retry": "Erneut versuchen", "close": "Schließen", "preview": "Vorschau", "duplicate": "Duplizieren", "archive": "Archivieren", "actions": "Aktionen", "refresh": "Aktualisieren", "status": "Status", "active": "Aktiv", "inactive": "Inaktiv", "yes": "Ja", "no": "Nein", "select": "Auswählen", "reset": "Zurücksetzen", "optional": "Optional", "required": "Erforderlich", "all": "Alle", "none": "Keine", "units": "Einheiten", "cm": "CM", "in": "ZOLL", "items": "{{count}} Elemente", "productsCount": "{{count}} Produkte", "categoriesCount": "{{count}} Kategorien", "rows": "Zeilen", "columns": "Spalten" },
    "navigation": { "overview": "Übersicht", "charts": "Größentabellen", "assignments": "Zuweisungen", "fitFinder": "Größenfinder", "analytics": "Analysen", "settings": "Einstellungen", "general": "Allgemein", "widget": "Widget-Design", "localization": "Lokalisierung", "billing": "Abrechnung & Pläne", "data": "Daten & Backup", "help": "Hilfe & Doku", "currentPlan": "Aktueller Plan" },
    "overview": { "title": "Stores Größentabelle & Passform-Berater", "subtitle": "Erstellen Sie Größentabellen und helfen Sie Käufern, die perfekte Passform zu finden.", "kpis": { "totalCharts": "Tabellen Gesamt", "activeCharts": "Aktive Tabellen", "productsWithCharts": "Produkte mit Tabelle", "productsWithoutCharts": "Produkte ohne Tabelle", "sizeGuideViews": "Größenguide-Aufrufe", "fitFinderUses": "Größenfinder-Nutzungen", "completionRate": "Abschlussrate", "mostViewedChart": "Meistgesehene Tabelle", "mostRecommendedSize": "Häufigste Empfehlung" }, "quickActions": "Schnellaktionen", "createChart": "Tabelle erstellen", "assignCharts": "Tabellen zuweisen", "customizeWidget": "Widget anpassen", "configureFitFinder": "Größenfinder einrichten" },
    "pluginStatus": { "title": "Größenguide Widget-Status", "active": "Aktiv", "notAdded": "Einrichtung erforderlich", "checking": "Prüfung...", "error": "Statusprüfung fehlgeschlagen", "descriptionActive": "Ihr Größenguide ist auf der Wix Stores Produktseite installiert.", "descriptionNotAdded": "Fügen Sie den Größenguide zu Ihrer Produktseite hinzu.", "descriptionError": "Widget-Platzierungsstatus konnte nicht geprüft werden.", "manage": "Im Editor verwalten", "add": "Größenguide hinzufügen", "retry": "Wiederholen", "addSuccess": "Größenguide erfolgreich hinzugefügt", "addError": "Automatisches Hinzufügen fehlgeschlagen.", "warningMissing": "Größentabellen sind aktiv, aber das Widget fehlt auf der Produktseite." },
    "charts": { "title": "Größentabellen", "subtitle": "Verwalten Sie alle Größentabellen und Maßanleitungen.", "create": "Größentabelle erstellen", "searchPlaceholder": "Größentabellen suchen...", "filterType": "Alle Typen", "filterStatus": "Alle Status", "allTypes": "Alle Typen", "allStatuses": "Alle Status", "emptyTitle": "Noch keine Größentabellen", "emptyDescription": "Erstellen Sie Ihre erste Größentabelle.", "deleteConfirmTitle": "Größentabelle löschen?", "deleteConfirmDesc": "Sind Sie sicher, dass Sie '{{name}}' löschen möchten?", "tableHeaderName": "Tabellenname", "tableHeaderType": "Kategorie / Typ", "tableHeaderUnit": "Standardeinheit", "tableHeaderAssignments": "Zuweisungen", "tableHeaderFitFinder": "Größenfinder", "tableHeaderStatus": "Status", "tableHeaderUpdated": "Zuletzt aktualisiert" },
    "fitFinder": { "title": "Smart Fit Finder", "subtitle": "Passform-Empfehlungen basierend auf Körpermaßen.", "statusToggle": "Fit Finder für diese Tabelle aktivieren", "storefrontTitle": "Größe finden", "stepOf": "Schritt {{current}} von {{total}}", "continueBtn": "Weiter", "backBtn": "Zurück", "calculateBtn": "Größe berechnen", "recommendedSizeTitle": "Ihre empfohlene Größe", "closestMatchDesc": "Basierend auf Ihren Maßen ist {{size}} die beste Wahl.", "betweenSizesTitle": "Sie liegen zwischen zwei Größen", "betweenSizesDesc": "Zwei passende Optionen:", "closerFit": "{{size}} für engere Passform", "moreRelaxedFit": "{{size}} für lockere Passform", "selectSizeBtn": "Größe {{size}} wählen", "startOverBtn": "Neu starten", "noRecommendation": "Berechnung nicht möglich." },
    "billing": { "currentPlanTitle": "Abonnementstatus", "starterPlan": "Starter-Plan", "proPlan": "Pro-Plan", "trialActive": "Kostenlose Testphase aktiv", "trialAvailable": "Testphase verfügbar", "daysRemaining": "Noch {{count}} Tage Testphase", "subscriptionActive": "Abonnement aktiv", "subscriptionCancelled": "Kündigung vorgemerkt", "activeUntil": "Aktiv bis {{date}}", "trialExpired": "Testphase abgelaufen", "paidExpired": "Abo abgelaufen", "billingUnknown": "Abrechnungsstatus unbekannt", "startTrialBtn": "Testphase starten", "subscribeBtn": "Jetzt abonnieren", "resubscribeBtn": "Abo reaktivieren", "reactivateBtn": "Reaktivieren", "choosePlanBtn": "Plan wählen" }
  },
  pt: {
    "common": { "save": "Salvar alterações", "cancel": "Cancelar", "delete": "Excluir", "edit": "Editar", "create": "Criar", "add": "Adicionar", "remove": "Remover", "search": "Pesquisar...", "filter": "Filtrar", "sort": "Ordenar", "back": "Voltar", "next": "Avançar", "continue": "Continuar", "loading": "Carregando...", "error": "Ocorreu um erro", "success": "Sucesso", "retry": "Tentar novamente", "close": "Fechar", "preview": "Pré-visualizar", "duplicate": "Duplicar", "archive": "Arquivar", "actions": "Ações", "refresh": "Atualizar", "status": "Status", "active": "Ativo", "inactive": "Inativo", "yes": "Sim", "no": "Não", "select": "Selecionar", "reset": "Redefinir", "optional": "Opcional", "required": "Obrigatório", "all": "Todos", "none": "Nenhum", "units": "Unidades", "cm": "CM", "in": "POL", "items": "{{count}} itens", "productsCount": "{{count}} produtos", "categoriesCount": "{{count}} categorias", "rows": "Linhas", "columns": "Colunas" },
    "navigation": { "overview": "Visão Geral", "charts": "Tabelas de Medidas", "assignments": "Atribuições", "fitFinder": "Provador Virtual", "analytics": "Métricas", "settings": "Configurações", "general": "Geral", "widget": "Design do Widget", "localization": "Idiomas", "billing": "Planos e Faturamento", "data": "Dados e Backup", "help": "Ajuda", "currentPlan": "Plano Atual" },
    "overview": { "title": "Stores Size Chart & Fit Guide", "subtitle": "Crie tabelas de medidas profissionais e ajude seus clientes a acertar no tamanho.", "kpis": { "totalCharts": "Total de Tabelas", "activeCharts": "Tabelas Ativas", "productsWithCharts": "Produtos com Tabela", "productsWithoutCharts": "Produtos sem Tabela", "sizeGuideViews": "Visualizações do Guia", "fitFinderUses": "Usos do Provador", "completionRate": "Taxa de Conclusão", "mostViewedChart": "Tabela Mais Vista", "mostRecommendedSize": "Tamanho Mais Recomendado" }, "quickActions": "Ações Rápidas", "createChart": "Criar Tabela", "assignCharts": "Atribuir Tabelas", "customizeWidget": "Personalizar Widget", "configureFitFinder": "Configurar Provador" },
    "pluginStatus": { "title": "Status do Guia de Tamanhos", "active": "Ativo", "notAdded": "Configuração necessária", "checking": "Verificando...", "error": "Falha na verificação", "descriptionActive": "Seu Guia de Tamanhos está instalado na página de produto.", "descriptionNotAdded": "Adicione o Guia de Tamanhos à página de produto da sua loja.", "descriptionError": "Não foi possível verificar a instalação do widget.", "manage": "Gerenciar no Editor", "add": "Adicionar Guia de Tamanhos", "retry": "Tentar Novamente", "addSuccess": "Guia de tamanhos adicionado com sucesso", "addError": "Não foi possível adicionar automaticamente.", "warningMissing": "Suas tabelas estão ativas, mas o widget não está instalado." },
    "charts": { "title": "Tabelas de Medidas", "subtitle": "Gerencie todas as tabelas e guias de medidas do seu catálogo.", "create": "Criar Tabela de Medidas", "searchPlaceholder": "Pesquisar tabelas...", "filterType": "Todos os Tipos", "filterStatus": "Todos os Status", "allTypes": "Todos os Tipos", "allStatuses": "Todos os Status", "emptyTitle": "Nenhuma tabela criada", "emptyDescription": "Crie sua primeira tabela de medidas.", "deleteConfirmTitle": "Excluir tabela?", "deleteConfirmDesc": "Tem certeza de que deseja excluir '{{name}}'?", "tableHeaderName": "Nome da Tabela", "tableHeaderType": "Categoria / Tipo", "tableHeaderUnit": "Unidade Padrão", "tableHeaderAssignments": "Atribuições", "tableHeaderFitFinder": "Provador Virtual", "tableHeaderStatus": "Status", "tableHeaderUpdated": "Última Atualização" },
    "fitFinder": { "title": "Smart Fit Finder", "subtitle": "Recomendações precisas de tamanho com base nas medidas dos clientes.", "statusToggle": "Ativar Provador Virtual para esta tabela", "storefrontTitle": "Descubra seu Tamanho", "stepOf": "Passo {{current}} de {{total}}", "continueBtn": "Continuar", "backBtn": "Voltar", "calculateBtn": "Ver Meu Tamanho", "recommendedSizeTitle": "Seu tamanho recomendado", "closestMatchDesc": "Com base nas suas medidas, o tamanho {{size}} é o ideal para você.", "betweenSizesTitle": "Você está entre dois tamanhos", "betweenSizesDesc": "Encontramos duas opções próximas:", "closerFit": "{{size}} para caimento mais justo", "moreRelaxedFit": "{{size}} para caimento mais folgado", "selectSizeBtn": "Selecionar Tamanho {{size}}", "startOverBtn": "Recomeçar", "noRecommendation": "Não foi possível calcular com essas medidas." },
    "billing": { "currentPlanTitle": "Status da Assinatura", "starterPlan": "Plano Starter", "proPlan": "Plano Pro", "trialActive": "Período de teste ativo", "trialAvailable": "Teste grátis disponível", "daysRemaining": "{{count}} dias restantes de teste", "subscriptionActive": "Assinatura ativa", "subscriptionCancelled": "Cancelamento agendado", "activeUntil": "Ativo até {{date}}", "trialExpired": "Período de teste encerrado", "paidExpired": "Assinatura expirada", "billingUnknown": "Status de cobrança desconhecido", "startTrialBtn": "Iniciar teste grátis", "subscribeBtn": "Assinar agora", "resubscribeBtn": "Reativar assinatura", "reactivateBtn": "Reativar", "choosePlanBtn": "Escolher plano" }
  },
  it: {
    "common": { "save": "Salva modifiche", "cancel": "Annulla", "delete": "Elimina", "edit": "Modifica", "create": "Crea", "add": "Aggiungi", "remove": "Rimuovi", "search": "Cerca...", "filter": "Filtra", "sort": "Ordina", "back": "Indietro", "next": "Avanti", "continue": "Continua", "loading": "Caricamento...", "error": "Si è verificato un errore", "success": "Operazione riuscita", "retry": "Riprova", "close": "Chiudi", "preview": "Anteprima", "duplicate": "Duplica", "archive": "Archivia", "actions": "Azioni", "refresh": "Aggiorna", "status": "Stato", "active": "Attivo", "inactive": "Inattivo", "yes": "Sì", "no": "No", "select": "Seleziona", "reset": "Reimposta", "optional": "Opzionale", "required": "Obbligatorio", "all": "Tutti", "none": "Nessuno", "units": "Unità", "cm": "CM", "in": "POLL", "items": "{{count}} elementi", "productsCount": "{{count}} prodotti", "categoriesCount": "{{count}} categorie", "rows": "Righe", "columns": "Colonne" },
    "navigation": { "overview": "Panoramica", "charts": "Tabelle taglie", "assignments": "Assegnazioni", "fitFinder": "Trova taglia", "analytics": "Analitica", "settings": "Impostazioni", "general": "Generale", "widget": "Design widget", "localization": "Localizzazione", "billing": "Piani e fatturazione", "data": "Dati e backup", "help": "Aiuto", "currentPlan": "Piano attuale" },
    "overview": { "title": "Stores Size Chart & Fit Guide", "subtitle": "Crea tabelle taglie professionali e aiuta i clienti a scegliere la misura corretta.", "kpis": { "totalCharts": "Tabelle totali", "activeCharts": "Tabelle attive", "productsWithCharts": "Prodotti con tabella", "productsWithoutCharts": "Prodotti senza tabella", "sizeGuideViews": "Visualizzazioni guida", "fitFinderUses": "Utilizzi Trova taglia", "completionRate": "Tasso di completamento", "mostViewedChart": "Tabella più vista", "mostRecommendedSize": "Taglia più raccomandata" }, "quickActions": "Azioni rapide", "createChart": "Crea tabella taglie", "assignCharts": "Assegna tabelle", "customizeWidget": "Personalizza widget", "configureFitFinder": "Configura Trova taglia" },
    "pluginStatus": { "title": "Stato del Widget Guida Taglie", "active": "Attivo", "notAdded": "Configurazione richiesta", "checking": "Verifica in corso...", "error": "Verifica fallita", "descriptionActive": "La tua Guida alle Taglie è installata nella pagina prodotto.", "descriptionNotAdded": "Aggiungi la Guida alle Taglie alla tua pagina prodotto Wix Stores.", "descriptionError": "Impossibile verificare lo stato del widget.", "manage": "Gestisci nell'Editor", "add": "Aggiungi Guida Taglie", "retry": "Riprova", "addSuccess": "Guida alle taglie aggiunta con successo", "addError": "Aggiunta automatica non riuscita.", "warningMissing": "Le tabelle sono attive ma il widget non è posizionato." },
    "charts": { "title": "Tabelle taglie", "subtitle": "Gestisci tutte le guide taglie e misure per il catalogo.", "create": "Crea tabella taglie", "searchPlaceholder": "Cerca tabelle...", "filterType": "Tutti i tipi", "filterStatus": "Tutti gli stati", "allTypes": "Tutti i tipi", "allStatuses": "Tutti gli stati", "emptyTitle": "Nessuna tabella", "emptyDescription": "Crea la tua prima tabella taglie.", "deleteConfirmTitle": "Eliminare la tabella?", "deleteConfirmDesc": "Sei sicuro di voler eliminare '{{name}}'?", "tableHeaderName": "Nome tabella", "tableHeaderType": "Categoria / Tipo", "tableHeaderUnit": "Unità predefinita", "tableHeaderAssignments": "Assegnazioni", "tableHeaderFitFinder": "Trova taglia", "tableHeaderStatus": "Stato", "tableHeaderUpdated": "Ultimo aggiornamento" },
    "fitFinder": { "title": "Smart Fit Finder", "subtitle": "Raccomandazioni taglie deterministiche sulle misure corporee.", "statusToggle": "Attiva Trova taglia per questa tabella", "storefrontTitle": "Trova la tua taglia", "stepOf": "Passaggio {{current}} di {{total}}", "continueBtn": "Continua", "backBtn": "Indietro", "calculateBtn": "Calcola la mia taglia", "recommendedSizeTitle": "La tua taglia consigliata", "closestMatchDesc": "In base alle tue misure, la taglia migliore è {{size}}.", "betweenSizesTitle": "Sei tra due taglie", "betweenSizesDesc": "Due opzioni vicine alle tue misure:", "closerFit": "{{size}} per una vestibilità più aderente", "moreRelaxedFit": "{{size}} per una vestibilità più morbida", "selectSizeBtn": "Scegli taglia {{size}}", "startOverBtn": "Ricomincia", "noRecommendation": "Calcolo non riuscito." },
    "billing": { "currentPlanTitle": "Stato abbonamento", "starterPlan": "Piano Starter", "proPlan": "Piano Pro", "trialActive": "Prova gratuita attiva", "trialAvailable": "Prova gratuita disponibile", "daysRemaining": "{{count}} giorni di prova rimanenti", "subscriptionActive": "Abbonamento attivo", "subscriptionCancelled": "Cancellazione in sospeso", "activeUntil": "Attivo fino al {{date}}", "trialExpired": "Prova gratuita terminata", "paidExpired": "Abbonamento scaduto", "billingUnknown": "Stato fatturazione sconosciuto", "startTrialBtn": "Inizia la prova gratuita", "subscribeBtn": "Abbonati ora", "resubscribeBtn": "Riattiva abbonamento", "reactivateBtn": "Riattiva", "choosePlanBtn": "Scegli piano" }
  },
  ar: {
    "common": { "save": "حفظ التغييرات", "cancel": "إلغاء", "delete": "حذف", "edit": "تعديل", "create": "إنشاء", "add": "إضافة", "remove": "إزالة", "search": "بحث...", "filter": "تصفية", "sort": "ترتيب", "back": "رجوع", "next": "التالي", "continue": "متابعة", "loading": "جاري التحميل...", "error": "حدث خطأ", "success": "تم بنجاح", "retry": "إعادة المحاولة", "close": "إغلاق", "preview": "معاينة", "duplicate": "تكرار", "archive": "أرشفة", "actions": "إجراءات", "refresh": "تحديث", "status": "الحالة", "active": "نشط", "inactive": "غير نشط", "yes": "نعم", "no": "لا", "select": "تحديد", "reset": "إعادة تعيين", "optional": "اختياري", "required": "مطلوب", "all": "الكل", "none": "لا شيء", "units": "الوحدات", "cm": "سم", "in": "بوصة", "items": "{{count}} عنصر", "productsCount": "{{count}} منتج", "categoriesCount": "{{count}} تصنيف", "rows": "الصفوف", "columns": "الأعمدة" },
    "navigation": { "overview": "نظرة عامة", "charts": "جداول المقاسات", "assignments": "التعيينات", "fitFinder": "مكتشف المقاس", "analytics": "التحليلات", "settings": "الإعدادات", "general": "عام", "widget": "تصميم الأداة", "localization": "اللغات والترجمة", "billing": "الاشتراكات والفواتير", "data": "البيانات والنسخ الاحتياطي", "help": "المساعدة", "currentPlan": "الخطة الحالية" },
    "overview": { "title": "Stores Size Chart & Fit Guide", "subtitle": "أنشئ جداول مقاسات احترافية وساعد العملاء في اختيار المقاس المثالي.", "kpis": { "totalCharts": "إجمالي الجداول", "activeCharts": "الجداول النشطة", "productsWithCharts": "منتجات بجداول", "productsWithoutCharts": "منتجات بدون جدول", "sizeGuideViews": "مشاهدات دليل المقاسات", "fitFinderUses": "استخدامات مكتشف المقاس", "completionRate": "معدل الإكمال", "mostViewedChart": "الجدول الأكثر مشاهدة", "mostRecommendedSize": "المقاس الأكثر ترشيحاً" }, "quickActions": "إجراءات سريعة", "createChart": "إنشاء جدول مقاسات", "assignCharts": "تعيين الجداول", "customizeWidget": "تخصيص الأداة", "configureFitFinder": "إعداد مكتشف المقاس" },
    "pluginStatus": { "title": "حالة أداة دليل المقاسات", "active": "نشط", "notAdded": "الإعداد مطلوب", "checking": "جاري الفحص...", "error": "فشل التحقق", "descriptionActive": "دليل المقاسات مثبت على صفحة منتجات Wix Stores الخاصة بك.", "descriptionNotAdded": "أضف دليل المقاسات إلى صفحة المنتج ليتمكن المتسوقون من رؤيته.", "descriptionError": "تعذر التحقق من حالة وضع الأداة.", "manage": "إدارة في المحرر", "add": "إضافة دليل المقاسات", "retry": "إعادة المحاولة", "addSuccess": "تمت إضافة دليل المقاسات بنجاح إلى صفحة المنتج", "addError": "تعذرت الإضافة التلقائية.", "warningMissing": "جداول المقاسات نشطة ولكن الأداة غير مثبتة في صفحة المنتج." },
    "charts": { "title": "جداول المقاسات", "subtitle": "إدارة جميع أدلة المقاسات والقياسات لمنتجاتك.", "create": "إنشاء جدول مقاسات", "searchPlaceholder": "بحث في الجداول...", "filterType": "جميع الأنواع", "filterStatus": "جميع الحالات", "allTypes": "جميع الأنواع", "allStatuses": "جميع الحالات", "emptyTitle": "لا توجد جداول مقاسات بعد", "emptyDescription": "أنشئ جدولك الأول لمساعدة العملاء على اختيار المقاس المناسب.", "deleteConfirmTitle": "حذف جدول المقاسات؟", "deleteConfirmDesc": "هل أنت متأكد من حذف '{{name}}'؟", "tableHeaderName": "اسم الجدول", "tableHeaderType": "النوع / التصنيف", "tableHeaderUnit": "الوحدة الافتراضية", "tableHeaderAssignments": "التعيينات", "tableHeaderFitFinder": "مكتشف المقاس", "tableHeaderStatus": "الحالة", "tableHeaderUpdated": "آخر تحديث" },
    "fitFinder": { "title": "مكتشف المقاس الذكي", "subtitle": "توصيات مقاسات دقيقة بناءً على قياسات الجسم.", "statusToggle": "تفعيل مكتشف المقاس الذكي لهذا الجدول", "storefrontTitle": "ابحث عن مقاسي", "stepOf": "الخطوة {{current}} من {{total}}", "continueBtn": "متابعة", "backBtn": "رجوع", "calculateBtn": "احسب مقاسي المناسب", "recommendedSizeTitle": "المقاس الموصى به لك", "closestMatchDesc": "بناءً على قياساتك، المقاس {{size}} هو الأنسب لك.", "betweenSizesTitle": "أنت بين مقاسين", "betweenSizesDesc": "وجدنا خيارين قريبين من قياساتك:", "closerFit": "{{size}} لمقاس أكثر إحكاماً", "moreRelaxedFit": "{{size}} لمقاس أكثر راحة وفضفاضة", "selectSizeBtn": "اختيار المقاس {{size}}", "startOverBtn": "البدء من جديد", "noRecommendation": "تعذر حساب التوصية بالقياسات المدخلة." },
    "billing": { "currentPlanTitle": "حالة الاشتراك", "starterPlan": "خطة Starter", "proPlan": "خطة Pro", "trialActive": "الفترة التجريبية نشطة", "trialAvailable": "فترة تجريبية متاحة", "daysRemaining": "متبقي {{count}} أيام في التجربة", "subscriptionActive": "الاشتراك نشط", "subscriptionCancelled": "إلغاء معلق", "activeUntil": "نشط حتى {{date}}", "trialExpired": "انتهت الفترة التجريبية", "paidExpired": "انتهى الاشتراك", "billingUnknown": "تعذر معرفة حالة الفوترة", "startTrialBtn": "بدء الفترة التجريبية", "subscribeBtn": "اشترك الآن", "resubscribeBtn": "إعادة تفعيل الاشتراك", "reactivateBtn": "إعادة التفعيل", "choosePlanBtn": "اختر خطة" }
  },
  ja: {
    "common": { "save": "変更を保存", "cancel": "キャンセル", "delete": "削除", "edit": "編集", "create": "作成", "add": "追加", "remove": "削除", "search": "検索...", "filter": "フィルター", "sort": "並び替え", "back": "戻る", "next": "次へ", "continue": "続ける", "loading": "読み込み中...", "error": "エラーが発生しました", "success": "成功", "retry": "再試行", "close": "閉じる", "preview": "プレビュー", "duplicate": "複製", "archive": "アーカイブ", "actions": "操作", "refresh": "更新", "status": "ステータス", "active": "有効", "inactive": "無効", "yes": "はい", "no": "いいえ", "select": "選択", "reset": "リセット", "optional": "任意", "required": "必須", "all": "すべて", "none": "なし", "units": "単位", "cm": "CM", "in": "IN", "items": "{{count}} 件", "productsCount": "{{count}} 商品", "categoriesCount": "{{count}} カテゴリ", "rows": "行", "columns": "列" },
    "navigation": { "overview": "概要", "charts": "サイズ表", "assignments": "割り当て", "fitFinder": "サイズファインダー", "analytics": "分析", "settings": "設定", "general": "一般", "widget": "ウィジェットデザイン", "localization": "多言語設定", "billing": "プランと請求", "data": "データとバックアップ", "help": "ヘルプ", "currentPlan": "現在のプラン" },
    "overview": { "title": "Stores サイズ表＆フィットガイド", "subtitle": "プロフェッショナルなサイズ表を作成し、顧客に最適なサイズを提案します。", "kpis": { "totalCharts": "サイズ表合計", "activeCharts": "有効なサイズ表", "productsWithCharts": "サイズ表あり商品", "productsWithoutCharts": "サイズ表なし商品", "sizeGuideViews": "サイズガイド表示数", "fitFinderUses": "フィット診断利用数", "completionRate": "診断完了率", "mostViewedChart": "最も見られたサイズ表", "mostRecommendedSize": "最多推薦サイズ" }, "quickActions": "クイックアクション", "createChart": "サイズ表を作成", "assignCharts": "商品を割り当て", "customizeWidget": "ウィジェットを編集", "configureFitFinder": "診断機能を設定" },
    "pluginStatus": { "title": "サイズガイドウィジェットの状態", "active": "有効", "notAdded": "設定が必要です", "checking": "確認中...", "error": "確認失敗", "descriptionActive": "サイズガイドはWix Stores商品ページに配置されています。", "descriptionNotAdded": "お客様がサイズ表を見られるように商品ページに設置してください。", "descriptionError": "設置状況を確認できませんでした。", "manage": "エディタで管理", "add": "サイズガイドを追加", "retry": "再試行", "addSuccess": "商品ページにサイズガイドを追加しました", "addError": "自動追加できませんでした。エディタで配置してください。", "warningMissing": "サイズ表は有効ですが、商品ページにウィジェットがありません。" },
    "charts": { "title": "サイズ表一覧", "subtitle": "商品カタログのすべてのサイズ表と採寸ガイドを管理します。", "create": "サイズ表を作成", "searchPlaceholder": "サイズ表を検索...", "filterType": "すべてのタイプ", "filterStatus": "すべてのステータス", "allTypes": "すべてのタイプ", "allStatuses": "すべてのステータス", "emptyTitle": "サイズ表がありません", "emptyDescription": "最初のサイズ表を作成しましょう。", "deleteConfirmTitle": "サイズ表を削除しますか？", "deleteConfirmDesc": "「{{name}}」を削除してもよろしいですか？", "tableHeaderName": "サイズ表名", "tableHeaderType": "カテゴリ / タイプ", "tableHeaderUnit": "既定単位", "tableHeaderAssignments": "割り当て", "tableHeaderFitFinder": "診断機能", "tableHeaderStatus": "ステータス", "tableHeaderUpdated": "最終更新" },
    "fitFinder": { "title": "Smart Fit Finder", "subtitle": "顧客の身体測定値に基づく正確なサイズ提案機能です。", "statusToggle": "このサイズ表でFit Finderを有効にする", "storefrontTitle": "マイサイズ診断", "stepOf": "ステップ {{current}} / {{total}}", "continueBtn": "次へ", "backBtn": "戻る", "calculateBtn": "おすすめサイズを診断", "recommendedSizeTitle": "あなたのおすすめサイズ", "closestMatchDesc": "測定結果に基づき、{{size}} サイズが最も適しています。", "betweenSizesTitle": "中間のサイズです", "betweenSizesDesc": "2つの候補が見つかりました：", "closerFit": "ぴったり着るなら {{size}}", "moreRelaxedFit": "ゆったり着るなら {{size}}", "selectSizeBtn": "サイズ {{size}} を選択", "startOverBtn": "最初からやり直す", "noRecommendation": "入力値からサイズを計算できませんでした。" },
    "billing": { "currentPlanTitle": "サブスクリプション状況", "starterPlan": "Starterプラン", "proPlan": "Proプラン", "trialActive": "無料トライアル中", "trialAvailable": "無料トライアルが利用可能", "daysRemaining": "残り {{count}} 日間のトライアル", "subscriptionActive": "有料プラン利用中", "subscriptionCancelled": "解約予定", "activeUntil": "{{date}} まで利用可能", "trialExpired": "トライアル期間が終了しました", "paidExpired": "プランの有効期限が切れました", "billingUnknown": "請求ステータスを確認できません", "startTrialBtn": "無料トライアルを開始", "subscribeBtn": "今すぐ契約する", "resubscribeBtn": "プランを再開", "reactivateBtn": "自動更新を再開", "choosePlanBtn": "プランを選択" }
  },
  "zh-CN": {
    "common": { "save": "保存更改", "cancel": "取消", "delete": "删除", "edit": "编辑", "create": "创建", "add": "添加", "remove": "移除", "search": "搜索...", "filter": "筛选", "sort": "排序", "back": "返回", "next": "下一步", "continue": "继续", "loading": "加载中...", "error": "发生错误", "success": "成功", "retry": "重试", "close": "关闭", "preview": "预览", "duplicate": "复制", "archive": "归档", "actions": "操作", "refresh": "刷新", "status": "状态", "active": "启用", "inactive": "未启用", "yes": "是", "no": "否", "select": "选择", "reset": "重置", "optional": "可选", "required": "必填", "all": "全部", "none": "无", "units": "单位", "cm": "厘米", "in": "英寸", "items": "{{count}} 项", "productsCount": "{{count}} 件商品", "categoriesCount": "{{count}} 个分类", "rows": "行", "columns": "列" },
    "navigation": { "overview": "概览", "charts": "尺码表", "assignments": "关联分配", "fitFinder": "智能尺码助手", "analytics": "数据分析", "settings": "设置", "general": "通用设置", "widget": "小部件设计", "localization": "多语言", "billing": "套餐与计费", "data": "数据备份", "help": "帮助与支持", "currentPlan": "当前套餐" },
    "overview": { "title": "Stores 尺码表与智能尺码助手", "subtitle": "为您的商品创建专业尺码表，帮助顾客轻松找到最合身的尺码。", "kpis": { "totalCharts": "尺码表总数", "activeCharts": "已启用尺码表", "productsWithCharts": "已关联商品数", "productsWithoutCharts": "未关联商品数", "sizeGuideViews": "尺码表浏览量", "fitFinderUses": "尺码助手使用次数", "completionRate": "诊断完成率", "mostViewedChart": "最常查看的尺码表", "mostRecommendedSize": "最常推荐尺码" }, "quickActions": "快捷操作", "createChart": "新建尺码表", "assignCharts": "关联商品", "customizeWidget": "自定义小部件", "configureFitFinder": "配置尺码助手" },
    "pluginStatus": { "title": "尺码指南小部件状态", "active": "正常运行", "notAdded": "需要配置", "checking": "检查中...", "error": "状态检查失败", "descriptionActive": "尺码指南小部件已正确安装在 Wix Stores 商品详情页。", "descriptionNotAdded": "请将尺码指南添加到 Wix Stores 商品详情页，以便顾客查看。", "descriptionError": "无法获取小部件配置状态。", "manage": "在编辑器中管理", "add": "添加尺码指南", "retry": "重试", "addSuccess": "已成功将尺码指南添加到商品详情页", "addError": "无法自动添加，请在 Wix 编辑器中手动放置。", "warningMissing": "尺码表已启用，但商品详情页未放置小部件。" },
    "charts": { "title": "尺码表管理", "subtitle": "管理商品目录的所有尺码表及测量说明。", "create": "创建尺码表", "searchPlaceholder": "搜索尺码表...", "filterType": "所有类型", "filterStatus": "所有状态", "allTypes": "所有类型", "allStatuses": "所有状态", "emptyTitle": "暂无尺码表", "emptyDescription": "立即创建您的第一个尺码表。", "deleteConfirmTitle": "删除尺码表？", "deleteConfirmDesc": "确定要删除“{{name}}”吗？此操作不可逆。", "tableHeaderName": "尺码表名称", "tableHeaderType": "分类 / 类型", "tableHeaderUnit": "默认单位", "tableHeaderAssignments": "关联商品", "tableHeaderFitFinder": "智能尺码", "tableHeaderStatus": "状态", "tableHeaderUpdated": "最后更新" },
    "fitFinder": { "title": "智能尺码推荐 (Smart Fit Finder)", "subtitle": "根据顾客的身材数据提供精准尺码推荐。", "statusToggle": "在此尺码表启用尺码助手", "storefrontTitle": "寻找我的合身尺码", "stepOf": "第 {{current}} 步，共 {{total}} 步", "continueBtn": "继续", "backBtn": "返回", "calculateBtn": "获取推荐尺码", "recommendedSizeTitle": "您的推荐尺码", "closestMatchDesc": "根据您的身体数据与版型偏好，推荐尺码为 {{size}}。", "betweenSizesTitle": "您的身材介于两个尺码之间", "betweenSizesDesc": "为您提供以下两个建议：", "closerFit": "选择 {{size}} 获取修身效果", "moreRelaxedFit": "选择 {{size}} 获取宽松舒适效果", "selectSizeBtn": "选择尺码 {{size}}", "startOverBtn": "重新测试", "noRecommendation": "根据输入数据无法计算出合适尺码。" },
    "billing": { "currentPlanTitle": "订阅套餐状态", "starterPlan": "Starter 基础版", "proPlan": "Pro 专业版", "trialActive": "免费试用中", "trialAvailable": "可享受免费试用", "daysRemaining": "试用期还剩 {{count}} 天", "subscriptionActive": "专业版订阅中", "subscriptionCancelled": "即将到期取消", "activeUntil": "有效期至 {{date}}", "trialExpired": "免费试用已结束", "paidExpired": "套餐已过期", "billingUnknown": "无法验证订阅状态", "startTrialBtn": "开始免费试用", "subscribeBtn": "立即订阅", "resubscribeBtn": "重新订阅", "reactivateBtn": "恢复自动续费", "choosePlanBtn": "选择套餐" }
  },
  "zh-TW": {
    "common": { "save": "儲存變更", "cancel": "取消", "delete": "刪除", "edit": "編輯", "create": "建立", "add": "新增", "remove": "移除", "search": "搜尋...", "filter": "篩選", "sort": "排序", "back": "返回", "next": "下一步", "continue": "繼續", "loading": "載入中...", "error": "發生錯誤", "success": "成功", "retry": "重試", "close": "關閉", "preview": "預覽", "duplicate": "複製", "archive": "封存", "actions": "操作", "refresh": "重新整理", "status": "狀態", "active": "啟用", "inactive": "停用", "yes": "是", "no": "否", "select": "選取", "reset": "重設", "optional": "選填", "required": "必填", "all": "全部", "none": "無", "units": "單位", "cm": "公分", "in": "英吋", "items": "{{count}} 項目", "productsCount": "{{count}} 件商品", "categoriesCount": "{{count}} 個分類", "rows": "列", "columns": "欄" },
    "navigation": { "overview": "總覽", "charts": "尺寸表", "assignments": "關聯分配", "fitFinder": "智能尺寸助手", "analytics": "數據分析", "settings": "設定", "general": "一般設定", "widget": "元件外觀設計", "localization": "多語系", "billing": "方案與計費", "data": "資料備份", "help": "說明與支援", "currentPlan": "目前方案" },
    "overview": { "title": "Stores 尺寸表與智能尺寸指南", "subtitle": "建立專業尺寸表，協助顧客挑選最合身的衣服與鞋碼。", "kpis": { "totalCharts": "尺寸表總數", "activeCharts": "已啟用尺寸表", "productsWithCharts": "已套用商品數", "productsWithoutCharts": "未套用商品數", "sizeGuideViews": "尺寸表瀏覽量", "fitFinderUses": "智能尺寸使用次數", "completionRate": "推薦完成率", "mostViewedChart": "最熱門尺寸表", "mostRecommendedSize": "最常推薦尺寸" }, "quickActions": "快速動作", "createChart": "建立尺寸表", "assignCharts": "指派商品", "customizeWidget": "自訂元件外觀", "configureFitFinder": "設定尺寸推薦" },
    "pluginStatus": { "title": "尺寸指南元件狀態", "active": "正常運行", "notAdded": "需要設定", "checking": "檢查中...", "error": "狀態檢查失敗", "descriptionActive": "尺寸指南元件已安裝於 Wix Stores 商品詳情頁。", "descriptionNotAdded": "請將尺寸指南元件加入商品詳情頁，讓顧客能輕鬆參考。", "descriptionError": "無法取得元件安裝狀態。", "manage": "在編輯器中管理", "add": "加入尺寸指南", "retry": "重試", "addSuccess": "已成功將尺寸指南加入商品詳情頁", "addError": "無法自動新增，請至 Wix 編輯器手動加入。", "warningMissing": "尺寸表已啟用，但商品詳情頁尚未加入小工具。" },
    "charts": { "title": "尺寸表管理", "subtitle": "管理商店目錄的所有尺寸表與丈量指南。", "create": "建立尺寸表", "searchPlaceholder": "搜尋尺寸表...", "filterType": "所有類型", "filterStatus": "所有狀態", "allTypes": "所有類型", "allStatuses": "所有狀態", "emptyTitle": "尚無尺寸表", "emptyDescription": "立即建立您的第一個尺寸表。", "deleteConfirmTitle": "刪除尺寸表？", "deleteConfirmDesc": "確定要刪除「{{name}}」嗎？此動作無法復原。", "tableHeaderName": "尺寸表名稱", "tableHeaderType": "分類 / 類型", "tableHeaderUnit": "預設單位", "tableHeaderAssignments": "套用商品", "tableHeaderFitFinder": "智能尺寸", "tableHeaderStatus": "狀態", "tableHeaderUpdated": "最後更新" },
    "fitFinder": { "title": "Smart Fit Finder 智能尺寸推薦", "subtitle": "依照顧客的身材數據給予最精準的尺寸建議。", "statusToggle": "在此尺寸表啟用尺寸推薦助手", "storefrontTitle": "尋找適合我的尺寸", "stepOf": "第 {{current}} 步，共 {{total}} 步", "continueBtn": "繼續", "backBtn": "返回", "calculateBtn": "取得推薦尺寸", "recommendedSizeTitle": "為您推薦的尺寸", "closestMatchDesc": "根據您的身體數據，推薦尺寸為 {{size}}。", "betweenSizesTitle": "您的身形介於兩個尺寸之間", "betweenSizesDesc": "為您提供以下建議：", "closerFit": "選取 {{size}} 穿著較為修身", "moreRelaxedFit": "選取 {{size}} 穿著較為寬鬆舒適", "selectSizeBtn": "選擇尺寸 {{size}}", "startOverBtn": "重新測量", "noRecommendation": "無法根據輸入數據計算推薦尺寸。" },
    "billing": { "currentPlanTitle": "訂閱方案狀態", "starterPlan": "Starter 基礎版", "proPlan": "Pro 專業版", "trialActive": "免費試用中", "trialAvailable": "可享有免費試用", "daysRemaining": "試用期剩餘 {{count}} 天", "subscriptionActive": "專業版訂閱中", "subscriptionCancelled": "到期後將取消", "activeUntil": "有效期限至 {{date}}", "trialExpired": "免費試用已結束", "paidExpired": "方案已過期", "billingUnknown": "無法確認訂閱狀態", "startTrialBtn": "開始免費試用", "subscribeBtn": "立即訂閱", "resubscribeBtn": "重新訂閱", "reactivateBtn": "恢復自動續訂", "choosePlanBtn": "選擇方案" }
  },
  nl: {
    "common": { "save": "Wijzigingen opslaan", "cancel": "Annuleren", "delete": "Verwijderen", "edit": "Bewerken", "create": "Maken", "add": "Toevoegen", "remove": "Verwijderen", "search": "Zoeken...", "filter": "Filteren", "sort": "Sorteren", "back": "Terug", "next": "Volgende", "continue": "Doorgaan", "loading": "Laden...", "error": "Er is een fout opgetreden", "success": "Succes", "retry": "Opnieuw proberen", "close": "Sluiten", "preview": "Voorbeeld", "duplicate": "Dupliceren", "archive": "Archiveren", "actions": "Acties", "refresh": "Vernieuwen", "status": "Status", "active": "Actief", "inactive": "Inactief", "yes": "Ja", "no": "Nee", "select": "Selecteren", "reset": "Herstellen", "optional": "Optioneel", "required": "Vereist", "all": "Alles", "none": "Geen", "units": "Eenheden", "cm": "CM", "in": "INCH", "items": "{{count}} items", "productsCount": "{{count}} producten", "categoriesCount": "{{count}} categorieën", "rows": "Rijen", "columns": "Kolommen" },
    "navigation": { "overview": "Overzicht", "charts": "Maattabellen", "assignments": "Toewijzingen", "fitFinder": "Maatwijzer", "analytics": "Statistieken", "settings": "Instellingen", "general": "Algemeen", "widget": "Widget ontwerp", "localization": "Talen", "billing": "Abonnement & Facturatie", "data": "Gegevens & Backup", "help": "Hulp", "currentPlan": "Huidig plan" }
  },
  pl: {
    "common": { "save": "Zapisz zmiany", "cancel": "Anuluj", "delete": "Usuń", "edit": "Edytuj", "create": "Utwórz", "add": "Dodaj", "remove": "Usuń", "search": "Szukaj...", "filter": "Filtruj", "sort": "Sortuj", "back": "Wstecz", "next": "Dalej", "continue": "Kontynuuj", "loading": "Ładowanie...", "error": "Wystąpił błąd", "success": "Sukces", "retry": "Spróbuj ponownie", "close": "Zamknij", "preview": "Podgląd", "duplicate": "Duplikuj", "archive": "Archiwizuj", "actions": "Akcje", "refresh": "Odśwież", "status": "Status", "active": "Aktywny", "inactive": "Nieaktywny", "yes": "Tak", "no": "Nie", "select": "Wybierz", "reset": "Resetuj", "optional": "Opcjonalnie", "required": "Wymagane", "all": "Wszystkie", "none": "Brak", "units": "Jednostki", "cm": "CM", "in": "CALE", "items": "{{count}} elementów", "productsCount": "{{count}} produktów", "categoriesCount": "{{count}} kategorii", "rows": "Wiersze", "columns": "Kolumny" },
    "navigation": { "overview": "Przegląd", "charts": "Tabele rozmiarów", "assignments": "Przypisania", "fitFinder": "Doradca rozmiaru", "analytics": "Analityka", "settings": "Ustawienia", "general": "Ogólne", "widget": "Wygląd widżetu", "localization": "Języki", "billing": "Plany i płatności", "data": "Dane i kopia", "help": "Pomoc", "currentPlan": "Aktualny plan" }
  },
  sv: {
    "common": { "save": "Spara ändringar", "cancel": "Avbryt", "delete": "Radera", "edit": "Redigera", "create": "Skapa", "add": "Lägg till", "remove": "Ta bort", "search": "Sök...", "filter": "Filtrera", "sort": "Sortera", "back": "Tillbaka", "next": "Nästa", "continue": "Fortsätt", "loading": "Laddar...", "error": "Ett fel uppstod", "success": "Lyckades", "retry": "Försök igen", "close": "Stäng", "preview": "Förhandsgranska", "duplicate": "Duplicera", "archive": "Arkivera", "actions": "Åtgärder", "refresh": "Uppdatera", "status": "Status", "active": "Aktiv", "inactive": "Inaktiv", "yes": "Ja", "no": "Nej", "select": "Välj", "reset": "Återställ", "optional": "Valfritt", "required": "Obligatoriskt", "all": "Alla", "none": "Inga", "units": "Enheter", "cm": "CM", "in": "TUM", "items": "{{count}} artiklar", "productsCount": "{{count}} produkter", "categoriesCount": "{{count}} kategorier", "rows": "Rader", "columns": "Kolumner" },
    "navigation": { "overview": "Översikt", "charts": "Storlekstabeller", "assignments": "Tilldelningar", "fitFinder": "Storlekshjälp", "analytics": "Analys", "settings": "Inställningar", "general": "Allmänt", "widget": "Widgetdesign", "localization": "Språk", "billing": "Fakturering & Planer", "data": "Data & Backup", "help": "Hjälp", "currentPlan": "Nuvarande plan" }
  },
  da: {
    "common": { "save": "Gem ændringer", "cancel": "Annuller", "delete": "Slet", "edit": "Rediger", "create": "Opret", "add": "Tilføj", "remove": "Fjern", "search": "Søg...", "filter": "Filtrer", "sort": "Sorter", "back": "Tilbage", "next": "Næste", "continue": "Fortsæt", "loading": "Indlæser...", "error": "Der opstod en fejl", "success": "Succes", "retry": "Prøv igen", "close": "Luk", "preview": "Forhåndsvisning", "duplicate": "Dupliker", "archive": "Arkiver", "actions": "Handlinger", "refresh": "Opdater", "status": "Status", "active": "Aktiv", "inactive": "Inaktiv", "yes": "Ja", "no": "Nej", "select": "Vælg", "reset": "Nulstil", "optional": "Valgfri", "required": "Påkrævet", "all": "Alle", "none": "Ingen", "units": "Enheder", "cm": "CM", "in": "TOMMER", "items": "{{count}} elementer", "productsCount": "{{count}} produkter", "categoriesCount": "{{count}} kategorier", "rows": "Rækker", "columns": "Kolonner" },
    "navigation": { "overview": "Oversigt", "charts": "Størrelsesguider", "assignments": "Tildelinger", "fitFinder": "Størrelsesfinder", "analytics": "Analyse", "settings": "Indstillinger", "general": "Generelt", "widget": "Widget design", "localization": "Sprog", "billing": "Fakturering & Planer", "data": "Data & Backup", "help": "Hjælp", "currentPlan": "Nuværende plan" }
  },
  no: {
    "common": { "save": "Lagre endringer", "cancel": "Avbryt", "delete": "Slett", "edit": "Rediger", "create": "Opprett", "add": "Legg til", "remove": "Fjern", "search": "Søk...", "filter": "Filtrer", "sort": "Sorter", "back": "Tilbake", "next": "Neste", "continue": "Fortsett", "loading": "Laster...", "error": "Det oppsto en feil", "success": "Vellykket", "retry": "Prøv igjen", "close": "Lukk", "preview": "Forhåndsvisning", "duplicate": "Dupliser", "archive": "Arkiver", "actions": "Handlinger", "refresh": "Oppdater", "status": "Status", "active": "Aktiv", "inactive": "Inaktiv", "yes": "Ja", "no": "Nei", "select": "Velg", "reset": "Tilbakestill", "optional": "Valgfritt", "required": "Påkrevd", "all": "Alle", "none": "Ingen", "units": "Enheter", "cm": "CM", "in": "TOMMER", "items": "{{count}} elementer", "productsCount": "{{count}} produkter", "categoriesCount": "{{count}} kategorier", "rows": "Rader", "columns": "Kolonner" },
    "navigation": { "overview": "Oversikt", "charts": "Størrelsestabeller", "assignments": "Tilordninger", "fitFinder": "Størrelsesfinner", "analytics": "Analyse", "settings": "Innstillinger", "general": "Generelt", "widget": "Widget-design", "localization": "Språk", "billing": "Fakturering og planer", "data": "Data og sikkerhetskopi", "help": "Hjelp", "currentPlan": "Gjeldende plan" }
  },
  fi: {
    "common": { "save": "Tallenna muutokset", "cancel": "Peruuta", "delete": "Poista", "edit": "Muokkaa", "create": "Luo", "add": "Lisää", "remove": "Poista", "search": "Hae...", "filter": "Suodata", "sort": "Järjestä", "back": "Takaisin", "next": "Seuraava", "continue": "Jatka", "loading": "Ladataan...", "error": "Tapahtui virhe", "success": "Onnistui", "retry": "Yritä uudelleen", "close": "Sulje", "preview": "Esikatselu", "duplicate": "Monista", "archive": "Arkistoi", "actions": "Toiminnot", "refresh": "Päivitä", "status": "Tila", "active": "Aktiivinen", "inactive": "Ei aktiivinen", "yes": "Kyllä", "no": "Ei", "select": "Valitse", "reset": "Palauta", "optional": "Valinnainen", "required": "Pakollinen", "all": "Kaikki", "none": "Ei mitään", "units": "Yksiköt", "cm": "CM", "in": "TUUMAA", "items": "{{count}} kohdetta", "productsCount": "{{count}} tuotetta", "categoriesCount": "{{count}} kategoriaa", "rows": "Rivit", "columns": "Sarakkeet" },
    "navigation": { "overview": "Yleiskatsaus", "charts": "Kokotaulukot", "assignments": "Määritykset", "fitFinder": "Koko-opas", "analytics": "Analytiikka", "settings": "Asetukset", "general": "Yleiset", "widget": "Widgetin ulkoasu", "localization": "Kielet", "billing": "Laskutus & Sopimukset", "data": "Tiedot & Varmuuskopiot", "help": "Ohje", "currentPlan": "Nykyinen sopimus" }
  },
  ko: {
    "common": { "save": "변경사항 저장", "cancel": "취소", "delete": "삭제", "edit": "수정", "create": "생성", "add": "추가", "remove": "제거", "search": "검색...", "filter": "필터", "sort": "정렬", "back": "뒤로", "next": "다음", "continue": "계속", "loading": "로딩 중...", "error": "오류가 발생했습니다", "success": "성공", "retry": "다시 시도", "close": "닫기", "preview": "미리보기", "duplicate": "복제", "archive": "보관", "actions": "작업", "refresh": "새로고침", "status": "상태", "active": "활성", "inactive": "비활성", "yes": "예", "no": "아니요", "select": "선택", "reset": "초기화", "optional": "선택사항", "required": "필수", "all": "전체", "none": "없음", "units": "단위", "cm": "CM", "in": "IN", "items": "{{count}}개 항목", "productsCount": "{{count}}개 상품", "categoriesCount": "{{count}}개 카테고리", "rows": "행", "columns": "열" },
    "navigation": { "overview": "개요", "charts": "사이즈 차트", "assignments": "상품 연결", "fitFinder": "스마트 핏 파인더", "analytics": "통계 분석", "settings": "설정", "general": "일반", "widget": "위젯 디자인", "localization": "다국어 설정", "billing": "요금제 및 결제", "data": "데이터 관리", "help": "도움말", "currentPlan": "현재 요금제" }
  },
  tr: {
    "common": { "save": "Değişiklikleri Kaydet", "cancel": "İptal", "delete": "Sil", "edit": "Düzenle", "create": "Oluştur", "add": "Ekle", "remove": "Kaldır", "search": "Ara...", "filter": "Filtrele", "sort": "Sırala", "back": "Geri", "next": "İleri", "continue": "Devam Et", "loading": "Yükleniyor...", "error": "Bir hata oluştu", "success": "Başarılı", "retry": "Tekrar Dene", "close": "Kapat", "preview": "Önizleme", "duplicate": "Çoğalt", "archive": "Arşivle", "actions": "İşlemler", "refresh": "Yenile", "status": "Durum", "active": "Aktif", "inactive": "Pasif", "yes": "Evet", "no": "Hayır", "select": "Seç", "reset": "Sıfırla", "optional": "İsteğe Bağlı", "required": "Gerekli", "all": "Tümü", "none": "Hiçbiri", "units": "Birimler", "cm": "CM", "in": "İNÇ", "items": "{{count}} öge", "productsCount": "{{count}} ürün", "categoriesCount": "{{count}} kategori", "rows": "Satırlar", "columns": "Sütunlar" },
    "navigation": { "overview": "Genel Bakış", "charts": "Beden Tabloları", "assignments": "Atamalar", "fitFinder": "Beden Bulucu", "analytics": "Analitik", "settings": "Ayarlar", "general": "Genel", "widget": "Widget Tasarımı", "localization": "Dil Seçenekleri", "billing": "Planlar ve Faturalandırma", "data": "Veri ve Yedekleme", "help": "Yardım", "currentPlan": "Mevcut Plan" }
  },
  id: {
    "common": { "save": "Simpan Perubahan", "cancel": "Batal", "delete": "Hapus", "edit": "Edit", "create": "Buat", "add": "Tambah", "remove": "Hapus", "search": "Cari...", "filter": "Filter", "sort": "Urutkan", "back": "Kembali", "next": "Berikutnya", "continue": "Lanjutkan", "loading": "Memuat...", "error": "Terjadi kesalahan", "success": "Berhasil", "retry": "Coba Lagi", "close": "Tutup", "preview": "Pratinjau", "duplicate": "Duplikat", "archive": "Arsipkan", "actions": "Tindakan", "refresh": "Segarkan", "status": "Status", "active": "Aktif", "inactive": "Tidak Aktif", "yes": "Ya", "no": "Tidak", "select": "Pilih", "reset": "Reset", "optional": "Opsional", "required": "Wajib", "all": "Semua", "none": "Tidak Ada", "units": "Satuan", "cm": "CM", "in": "INCI", "items": "{{count}} item", "productsCount": "{{count}} produk", "categoriesCount": "{{count}} kategori", "rows": "Baris", "columns": "Kolom" },
    "navigation": { "overview": "Ikhtisar", "charts": "Tabel Ukuran", "assignments": "Penetapan", "fitFinder": "Pencari Ukuran", "analytics": "Analitik", "settings": "Pengaturan", "general": "Umum", "widget": "Desain Widget", "localization": "Bahasa", "billing": "Paket & Tagihan", "data": "Data & Cadangan", "help": "Bantuan", "currentPlan": "Paket Saat Ini" }
  },
  hi: {
    "common": { "save": "बदलाव सहेजें", "cancel": "रद्द करें", "delete": "हटाएं", "edit": "संपादित करें", "create": "बनाएं", "add": "जोड़ें", "remove": "हटाएं", "search": "खोजें...", "filter": "फ़िल्टर", "sort": "क्रमबद्ध करें", "back": "पीछे", "next": "आगे", "continue": "जारी रखें", "loading": "लोड हो रहा है...", "error": "एक त्रुटि हुई", "success": "सफल", "retry": "पुनः प्रयास करें", "close": "बंद करें", "preview": "पूर्वावलोकन", "duplicate": "प्रतिलिपि बनाएं", "archive": "संग्रहीत करें", "actions": "क्रियाएं", "refresh": "ताज़ा करें", "status": "स्थिति", "active": "सक्रिय", "inactive": "निष्क्रिय", "yes": "हाँ", "no": "नहीं", "select": "चुनें", "reset": "रीसेट", "optional": "वैकल्पिक", "required": "आवश्यक", "all": "सभी", "none": "कोई नहीं", "units": "इकाइयां", "cm": "सेमी", "in": "इंच", "items": "{{count}} आइटम", "productsCount": "{{count}} उत्पाद", "categoriesCount": "{{count}} श्रेणियां", "rows": "पंक्तियाँ", "columns": "कॉलम" },
    "navigation": { "overview": "अवलोकन", "charts": "आकार चार्ट", "assignments": "असाइनमेंट", "fitFinder": "आकार खोजक", "analytics": "विश्लेषण", "settings": "सेटिंग्स", "general": "सामान्य", "widget": "विजेट डिज़ाइन", "localization": "स्थानीयकरण", "billing": "बिलिंग और योजनाएं", "data": "डेटा और बैकअप", "help": "सहायता", "currentPlan": "वर्तमान योजना" }
  }
};

function deepMerge(target, source) {
  const result = { ...source };
  for (const key of Object.keys(source)) {
    if (target && target[key] !== undefined) {
      if (typeof source[key] === 'object' && source[key] !== null && !Array.isArray(source[key])) {
        result[key] = deepMerge(target[key], source[key]);
      } else {
        result[key] = target[key];
      }
    }
  }
  return result;
}

const allLocales = [
  'es', 'fr', 'de', 'pt', 'it', 'nl', 'pl', 'sv', 'da', 'no',
  'fi', 'ja', 'ko', 'zh-CN', 'zh-TW', 'ar', 'tr', 'id', 'hi'
];

for (const loc of allLocales) {
  const custom = langPacks[loc] || {};
  const full = deepMerge(custom, en);
  const outPath = path.resolve(`src/i18n/locales/${loc}.json`);
  fs.writeFileSync(outPath, JSON.stringify(full, null, 2), 'utf8');
}

console.log('Successfully generated all 20 locale files with valid JSON.');

